const  level1  = new Level(
    [],
    [
      new Wolken("img/5_background/layers/4_clouds/1.png"),
      new Wolken("img/5_background/layers/4_clouds/2.png"),
    ],
    [],
    [
      new BackgroundObject("img/5_background/layers/air.png", -1023),
      new BackgroundObject("img/5_background/layers/3_third_layer/2.png", -1023),
      new BackgroundObject("img/5_background/layers/2_second_layer/2.png", -1023),
      new BackgroundObject("img/5_background/layers/1_first_layer/2.png", -1023),
      new BackgroundObject("img/5_background/layers/air.png", 0),
      new BackgroundObject("img/5_background/layers/3_third_layer/1.png", 0),
      new BackgroundObject("img/5_background/layers/2_second_layer/1.png", 0),
      new BackgroundObject("img/5_background/layers/1_first_layer/1.png", 0),
      new BackgroundObject("img/5_background/layers/air.png", 1023),
      new BackgroundObject("img/5_background/layers/3_third_layer/2.png", 1023),
      new BackgroundObject("img/5_background/layers/2_second_layer/2.png", 1023),
      new BackgroundObject("img/5_background/layers/1_first_layer/2.png", 1023),
      new BackgroundObject("img/5_background/layers/air.png", 1023 * 2),
      new BackgroundObject("img/5_background/layers/3_third_layer/1.png",1023 * 2),
      new BackgroundObject("img/5_background/layers/2_second_layer/1.png",1023 * 2),
      new BackgroundObject("img/5_background/layers/1_first_layer/1.png",1023 * 2),
      new BackgroundObject("img/5_background/layers/air.png", 1023 * 3),
      new BackgroundObject("img/5_background/layers/3_third_layer/2.png", 1023 * 3),
      new BackgroundObject("img/5_background/layers/2_second_layer/2.png",1023 * 3),
      new BackgroundObject("img/5_background/layers/1_first_layer/2.png",1023 * 3),
      new BackgroundObject("img/5_background/layers/air.png", 1023 * 4),
      new BackgroundObject("img/5_background/layers/3_third_layer/1.png",1023 * 4),
      new BackgroundObject("img/5_background/layers/2_second_layer/1.png",1023 * 4),
      new BackgroundObject("img/5_background/layers/1_first_layer/1.png",1023 * 4),
      new BackgroundObject("img/5_background/layers/air.png", 1023 * 5),      
      new BackgroundObject("img/5_background/layers/3_third_layer/2.png", 1023 * 5),
      new BackgroundObject("img/5_background/layers/2_second_layer/2.png", 1023 * 5),
      new BackgroundObject("img/5_background/layers/1_first_layer/2.png", 1023 * 5),
      new BackgroundObject("img/5_background/layers/air.png", 1023 * 6),
      new BackgroundObject("img/5_background/layers/3_third_layer/1.png",1023 * 6),
      new BackgroundObject("img/5_background/layers/2_second_layer/1.png",1023 * 6),
      new BackgroundObject("img/5_background/layers/1_first_layer/1.png",1023 * 6),
    ]
  );

